---

- name: Install required wget utility packages
  yum:
    name: wget
    state: present

- name: Install required git utility packages
  yum:
    name: git
    state: present

- name: Install required net-tools utility packages
  yum:
    name: net-tools
    state: present

- name: Install required bind-utils utility packages
  yum:
    name: bind-utils
    state: present

- name: Install required iptables-services utility packages
  yum:
    name: iptables-services
    state: present

- name: Install required bridge-utils utility packages
  yum:
    name: bridge-utils
    state: present

- name: Install required bash-completion utility packages
  yum:
    name: bash-completion
    state: present

- name: reload systemd
  shell: systemctl daemon-reload

- name: Install epel repo
  yum:
    name: epel-release
    state: present

- name: Install the packages for Ansible # yum -y --enablerepo=epel install ansible pyOpenSSL
  yum:
    name: pyOpenSSL
    state: present

- name: Install Ansible # yum -y --enablerepo=epel install ansible pyOpenSSL
  yum:
    name: ansible
    state: present

- name: Add docker repository
  yum_repository:
    name: 'Docker'
    description: 'Docker yum repository'
    baseurl: 'https://yum.dockerproject.org/repo/main/centos/7/'
    gpgkey: 'https://yum.dockerproject.org/gpg'
    gpgcheck: yes

- name: Install latest version of Docker
  yum:
    name: docker-1.10.3-44.el7.centos
    state: present

- name: Enable the docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Create docker service configuration (/etc/systemd/system/docker.service.d) directory
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: Set up docker service configuration
  template: src=docker.sysconfig.conf.j2 dest=/etc/sysconfig/docker owner=root group=root mode=0644

- name: reload systemctl daemon
  shell: systemctl daemon-reload

- name: restart docker
  service: name=docker state=restarted

- name: Clone opensift ansible project
  shell: /usr/bin/git clone https://github.com/openshift/openshift-ansible
  args:
    chdir: /home/vagrant
    creates: /home/vagrant/openshift-ansible
